on:
    push:

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: verify conventional commits
              uses: taskmedia/action-conventional-commits@v1.1.7
              with: 
                  types: fix|feat|revert|chore|docs|ci|build|refactor|style|test





      

          
       
