on:
    push:
    workflow_dispatch:

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: verify conventional commits
              uses: taskmedia/action-conventional-commits@v1.1.7
      

          
       
